import { BASE_URL } from "../constants/runtime";

const THUMB_SMALL_WIDTH = 96;
const THUMB_LARGE_WIDTH = 192;

export interface CatalogImageSourceSet {
  src: string;
  srcSet: string;
  fullSrc: string;
  sizes: string;
}

function normalizePath(path: string): string {
  return path.replace(/\\/g, "/").replace(/^\/+/, "");
}

function withBase(path: string): string {
  const base = BASE_URL.endsWith("/") ? BASE_URL : `${BASE_URL}/`;
  return `${base}${normalizePath(path)}`;
}

function stripImagesPrefix(path: string): string {
  const normalized = normalizePath(path);
  return normalized.startsWith("images/") ? normalized.slice("images/".length) : normalized;
}

function stripExtension(path: string): string {
  const dot = path.lastIndexOf(".");
  return dot === -1 ? path : path.slice(0, dot);
}

function buildThumbRelativePath(catalogImagePath: string, width: number): string {
  const stem = stripExtension(stripImagesPrefix(catalogImagePath));
  return `images-thumbs/${stem}.w${width}.webp`;
}

/**
 * Build responsive catalog image sources. Thumbnails are generated by
 * scripts/generate-catalog-thumbnails.ts.
 */
export function buildCatalogImageSourceSet(catalogImagePath: string, sizes: string): CatalogImageSourceSet {
  const fullSrc = withBase(catalogImagePath);
  const smallSrc = withBase(buildThumbRelativePath(catalogImagePath, THUMB_SMALL_WIDTH));
  const largeSrc = withBase(buildThumbRelativePath(catalogImagePath, THUMB_LARGE_WIDTH));

  return {
    src: smallSrc,
    srcSet: `${smallSrc} ${THUMB_SMALL_WIDTH}w, ${largeSrc} ${THUMB_LARGE_WIDTH}w`,
    fullSrc,
    sizes,
  };
}
