/**
 * Backward-compatible constants façade.
 * Domain-specific constants now live in `src/constants/*`.
 */
export { BASE_URL, FEATURE_MINI3D_AUTOROTATE } from "./constants/runtime";
export { CONNECTOR_ICON_MAP } from "./constants/connector-icons";
export { CONNECTOR_NAME_OPTIONS, CONNECTOR_KIND_OPTIONS } from "./constants/connector-kinds";
export {
  ZOOM_MIN,
  ZOOM_MAX,
  ZOOM_STEP,
  PINCH_DETECTION_THRESHOLD,
  MM_TO_PX,
  LONG_PRESS_MS,
  WHEEL_PIVOT_MS,
  WHEEL_THROTTLE_MS,
  WHEEL_TRANSITION_MS,
  DEBOUNCE_SAVE_MS,
  DRAG_THRESHOLD_PX,
  MOVE_THRESHOLD_PX,
  HISTORY_DEPTH,
  WHEEL_ZOOM_FACTOR,
} from "./constants/interaction";
export { TOOLBAR_GAP_PX, TOOLBAR_HEIGHT_PX, TILE_SIZE_BASE, DEFAULT_PLACEMENT_FALLBACK } from "./constants/layout";
export { DEVICE_TYPE_ORDER, DEVICE_TYPE_LABEL } from "./constants/catalog";
export { initialObjects, DEFAULT_OBJECT_COLOR } from "./constants/defaults";

// Cable constants live in their own module; re-export here for compatibility.
export {
  CABLE_TERMINAL_START_COLOR,
  CABLE_TERMINAL_END_COLOR,
  CABLE_COLORS,
  CABLE_COLOR_OPTIONS,
} from "./constants/cables";
export type { CableColor } from "./constants/cables";
export {
  CABLE_PATHS_STROKE_WIDTH_MM,
  CABLE_PATHS_HALO_EXTRA_MM,
  CABLE_PATHS_SELECTED_CABLE_HALO_COLOR,
  CABLE_PATHS_ENDPOINT_DOT_RADIUS_MM,
  CABLE_PATHS_ENDPOINT_DOT_STROKE,
  CABLE_PATHS_ENDPOINT_DOT_STROKE_WIDTH_MM,
  CABLE_PATHS_CANVAS_HALF,
  CABLE_PATHS_CANVAS_SIZE,
  CABLE_PATHS_Z_INDEX,
  CABLE_PATHS_HIT_STROKE_MM,
  CABLE_PATHS_HANDLE_REMOVE_PRESS_MS,
  CABLE_PATHS_HANDLE_DRAG_THRESHOLD_PX,
  CABLE_PATHS_DOUBLE_TAP_TIME_WINDOW_MS,
  CABLE_PATHS_DOUBLE_TAP_MAX_DISTANCE_PX,
  CABLE_PATHS_INSERT_FLASH_RADIUS_MM,
  CABLE_PATHS_INSERT_FLASH_DURATION_MS,
  CABLE_PATHS_HANDLE_HALO_RADIUS_MM,
  CABLE_PATHS_HANDLE_DOT_RADIUS_MM,
  CABLE_PATHS_MID_HANDLE_FILL,
  CABLE_PATHS_DOUBLE_CLICK_DETAIL_THRESHOLD,
  CABLE_PATHS_MIN_SEGMENT_LENGTH,
  CABLE_PATHS_LABEL_FONT_SIZE_MM,
  CABLE_PATHS_LABEL_TEXT_LINE_HEIGHT_MM,
  CABLE_PATHS_LABEL_TEXT_CHAR_WIDTH_MM,
  CABLE_PATHS_LABEL_TEXT_MIN_WIDTH_MM,
  CABLE_PATHS_LABEL_ICON_SIZE_MM,
  CABLE_PATHS_LABEL_ICON_GAP_MM,
  CABLE_PATHS_LABEL_TERMINAL_CLEARANCE_MM,
} from "./constants/cablePaths";
export {
  CABLE_LAYER_CURRENT_CABLE_STROKE,
  CABLE_LAYER_CURRENT_CABLE_OPACITY,
  CABLE_LAYER_CURRENT_CABLE_DASH_SCALE,
  CABLE_LAYER_CURRENT_CABLE_GAP_SCALE,
  CABLE_LAYER_STROKE_WIDTH_MM,
  CABLE_LAYER_ENDPOINT_DOT_RADIUS_PX,
  CABLE_LAYER_ENDPOINT_DOT_STROKE,
  CABLE_LAYER_ENDPOINT_DOT_STROKE_WIDTH_PX,
  CABLE_LAYER_LENGTH_COMPARE_EPSILON_MM,
  CABLE_LAYER_LENGTH_POPUP_Y_OFFSET_PX,
  CABLE_LAYER_DOUBLE_TAP_MS,
  CABLE_LAYER_DOUBLE_TAP_MAX_DISTANCE_PX,
  CABLE_LAYER_ACTIONS_SELECTOR,
  CABLE_LAYER_ADD_BUTTON_SELECTOR,
} from "./constants/cableLayerOverlay";
